### ISSUE TITLE
[Feature Request] - Need of ELK Beats Integration

### ISSUE THREAD

**Issue by ajeetraina** [openusm/openusm#6]
It would be great to see how ELK Filebeat - ELKF gets integrated too under OpenUSM. Would love to contribute.

**Comment by abendigeri** [comment]
Wow!! Thats a great feature to be added to OpenUSM.
Happy to Contribute

**Comment by ajeetraina** [comment]
Tested sensor logs exporter using ELK and it just works great. Currently working over the doc.

**Comment by ajeetraina** [comment]
The Filebeat integration is planned for v1.1 release and hence parking it right now.
